import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";

const pretendard = localFont({
	src: "../public/fonts/PretendardVariable.ttf",
	display: "swap",
	weight: "100 900",
	variable: "--font-pretendard",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ko" className={pretendard.variable}>
			<body className="antialiased">
				<div className="flex min-h-screen bg-[var(--dnd-bg-normal)]">
					<Sidebar />
					<main className="flex-1 ml-[260px]">{children}</main>
				</div>
			</body>
		</html>
	);
}
